Models/Dog.cs
using System.ComponentModel.DataAnnotations;

namespace Dogs.Models
{
    public class Dog
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Введите название породы!")]
        [MaxLength(50)]
        [Display(Name ="Название породы")]
        
        public string Breed { get; set; }
        [Required(ErrorMessage = "Введите название породы по-английски!")]
        [MaxLength(50)]
        [Display(Name = "Название породы по-английски")]
        public string BreedInEnglish { get; set; }
        [Required(ErrorMessage = "Введите происхождение породы!")]
        [MaxLength(30)]
        [Display(Name = "Происхождение породы")]
        public string Origin { get; set;}
        
        [Required]
        [Display(Name = "Добавьте изображение")]
        [DataType(DataType.Upload)]
        public string ImageUrl { get; set; }
        [Display(Name = "Описание поведения и характера")]
        public string BehaviorCharacter { get; set; }
        [Display(Name = "История породы")]
        public string HistoryOfBreed { get; set; }

        [Display(Name = "Выберите группу FCI")]
        public int FCICategoryId { get; set; }
        
        public FCICategory FCICategory { get; set; }
        [Display(Name = "Выберите назначение")]
        public IEnumerable<DogTag> DogTags { get; set; }

    }
}

Controllers/DogController.cs
using Dogs.Helpers;
using Dogs.Models;
using Dogs.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Dogs.Extensions;
using System.Drawing;

namespace Dogs.Controllers
{
    public class DogController:Controller
    {
        private readonly DogDbContext dogDbContext;

        public DogController(DogDbContext dogDbContext) 
        {
            this.dogDbContext = dogDbContext;
        }
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.fciCategories = new SelectList(dogDbContext.FCICategories, "Id", "Name");
            ViewBag.tags = new MultiSelectList(dogDbContext.Tags, "Id", "Name");
            return View();
        }
        [HttpGet]

        public IActionResult Index( string? searchBreed=null,int? tagId=null,int? fciCategoryId=null,int page=1)
        {
            
            var dogs=dogDbContext.Dogs.Include(x=>x.DogTags).ThenInclude(x=>x.Tag).Include(x=>x.FCICategory).OrderBy(x=>x.Breed);
            if(searchBreed !=null)
            {
                dogs = (IOrderedQueryable<Dog>)dogs.Where(x => x.Breed == searchBreed);
            }
        
            if(fciCategoryId != null && tagId !=null)
            {
                dogs = (IOrderedQueryable<Dog>)dogs.Where(x => x.FCICategoryId == fciCategoryId && x.DogTags.All (x => x.TagId == tagId));
            }
            else if(fciCategoryId!=null)
            {
                dogs= (IOrderedQueryable<Dog>)dogs.Where(x=>x.FCICategoryId==fciCategoryId);
            }
            else if (tagId != null)
            {
                 dogs = (IOrderedQueryable<Dog>)dogs.Where(x=>x.DogTags.Any(x=>x.TagId==tagId));
            }

            var model = new IndexViewModel();
            int totalP = (int)Math.Ceiling(dogs.Count() / (double)model.LimitPage);
            dogs = (IOrderedQueryable<Dog>)dogs.Skip((page - 1) * model.LimitPage).Take(model.LimitPage);
            model.Dogs = dogs;
            model.Tags = dogDbContext.Tags;
            model.FCICategories = dogDbContext.FCICategories;
            model.RecentDogs = dogDbContext.Dogs.OrderByDescending(x => x.Id).Take(3);
            model.CurrentPages = page;
            model.TotalPages = totalP;
            model.SelectedFCICategoryId = fciCategoryId;
            model.SelectedTagId = tagId;
            model.SearchBreed = searchBreed;
            return View(model);
        }
        


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(Dog dog, IFormFile Image, int[]tags)
        {

            dog.ImageUrl = await FileUploadHelper.UploadAsync(Image);           
            TempData["status"] = "Великолепно! Добавлена новая порода!";            
            await dogDbContext.Dogs.AddAsync(dog);
            await dogDbContext.SaveChangesAsync();
            //foreach (var dogTag in tags)
            //{
            //    var tmpDogTag = new DogTag() { DogId = dog.Id, TagId = dogTag };
            //    dogDbContext.DogTags.Add(tmpDogTag);
            //    await dogDbContext.SaveChangesAsync();
            //}
            dogDbContext.DogTags.AddRange(tags.Select(a =>  new DogTag() { DogId = dog.Id, TagId = a }));
            await dogDbContext.SaveChangesAsync();
            //foreach (var item in tags)
            //{
            //    dogDbContext.DogTags.Add(new DogTag { TagId = item, DogId = dog.Id });
            //}
            //await dogDbContext.SaveChangesAsync();
            return RedirectToAction("Add");
        
            //return View(dog);
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            var dogs = dogDbContext.Dogs
                .Include(x => x.DogTags).ThenInclude(x => x.Tag)
                .Include(x=>x.FCICategory)
                .FirstOrDefault(dogs => dogs.Id == id);
            return View(dogs);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var dogs = dogDbContext.Dogs.Find(id);

            ViewBag.fciCategories = new SelectList(dogDbContext.FCICategories, "Id", "Name");

            var selectedTagIds = dogDbContext.DogTags.Where(x => x.DogId == id).Select(x => x.TagId);
            ViewBag.tags = new MultiSelectList(dogDbContext.Tags, "Id", "Name", selectedTagIds);            

            return View(dogs);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var dogs = dogDbContext.Dogs.Find(id);           
            return View(dogs);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var dogs = dogDbContext.Dogs.Find(id);
            dogDbContext.Dogs.Remove(dogs);
            await dogDbContext.SaveChangesAsync();
            TempData["status"] = $"Вы успешно удалили породу {dogs.Breed}!";
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Dog dog, IFormFile Image, int[] tags)
        {
            if (Image != null)
            {
                var path = await FileUploadHelper.UploadAsync(Image);
                dog.ImageUrl = path;
            }

            dogDbContext.Dogs.Update(dog);
            await dogDbContext.SaveChangesAsync();


            var dogWithTags = dogDbContext.Dogs.Include(x =>x.DogTags).FirstOrDefault(x => x.Id == dog.Id);
            int a = 0;
            dogDbContext.UpdateManyToMany(
                dogWithTags.DogTags,
                tags.Select(x => new DogTag { DogId = dog.Id, TagId = x }),
                x => x.TagId
                );
            await dogDbContext.SaveChangesAsync();
            TempData["status"] = "Отлично! Вы изменили данные породы!";


            return RedirectToAction("Index");
        }

    }
}

ViewComponents/PaginationViewComponent.cs
using Dogs.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Dogs.ViewComponents
{
    public class PaginationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(int currentPage, int totalPages, int limit,int? tagId,int?fciCategoriId)
        {
            
            PaginationViewModel paginationViewModel = new PaginationViewModel()
            {
                TotalPages = totalPages,
                CurrentPage = currentPage,
                LimitItem=limit,
                TagId=tagId,
                FciCategoryId=fciCategoriId
            };
            return View("Pagination",paginationViewModel); 
        }
    }
}

Views/Dog/Add.cshtml
@model Dog
@{
    ViewData["Title"] = "Add";
}
@if (TempData.ContainsKey("status"))
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>@TempData["status"]</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<h1>Добавьте породу</h1>

<div class="row" >
    <div class="col-6">
        <form asp-controller="Dog" asp-action="Add" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="Breed"></label>
                <input asp-for="Breed" class="form-control" />
                <span asp-validation-for="Breed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BreedInEnglish"></label>
                <input asp-for="BreedInEnglish" class="form-control" />
                <span asp-validation-for="BreedInEnglish" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Origin"></label>
                <input asp-for="Origin" class="form-control" />
                <span asp-validation-for="Origin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FCICategoryId"></label>
                <select asp-for="FCICategoryId" asp-items="ViewBag.fciCategories" class="form-control">
                    
                </select>                
            </div> 
            <div class="form-group">
                <label asp-for="DogTags"></label>
            <select name="tags" asp-items="ViewBag.tags" multiple class="form-select chosen-select" aria-label="Default select example">
            </select>
            </div>
            <div class="mb-3">
                <label for="formFile" class="form-label">Добавьте изображение</label>
                <input class="form-control" name="Image" type="file" id="formFile" multiple required>
            </div>
            <div class="form-group">
                <label asp-for="BehaviorCharacter"></label>
                <textarea asp-for="BehaviorCharacter" class="form-control" rows="10"></textarea>
                <span asp-validation-for="BehaviorCharacter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HistoryOfBreed"></label>
                <textarea asp-for="HistoryOfBreed" class="form-control" rows="10"></textarea>
                <span asp-validation-for="HistoryOfBreed" class="text-danger"></span>
            </div>
            <button class="btn btn-outline-primary w-25 mt-2">Добавить</button>
        </form>
    </div>
</div>


@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Views/Dog/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}
@model Dog

<h1>Вы уверены, что хотите удалить @Model.Breed?</h1>


<div class="row">
    <div class="col-4">
        <a asp-action="Index" asp-controller="Dog" class="btn btn-danger w-100">Отмена</a>
    </div>
    <div class="col-4">
        <form asp-action="Delete" asp-controller="Dog" method="post">
            <input type="hidden" asp-for="Id" />
            <button class="btn btn-success w-100">Да</button>
        </form>
    </div>
</div>

Views/Dog/Details.cshtml
@model Dog
@{
    ViewData["Title"] = "Details";
}

<h1>FCI Group @Model.FCICategory.Name | @Model.Breed</h1>


<div class="card" >
    <div class="row g-0">
        <div class="col-md-4">
            <img src="@Model.ImageUrl" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                @if (Model.DogTags.Count() > 0)
                {
                    @foreach (var item in Model.DogTags)
                    {
                        <span class="badge bg-info rounded-pill"><em>Назначение: @item.Tag.Name</em> </span>
                    }
                }
                else
                {
                    <span class="badge bg-info rounded-pill"><em>Назначение: None</em> </span>
                }
                <h5 class="card-title">@Model.BreedInEnglish</h5>
                <p class="card-text "><i>@Model.Origin</i></p>
                <h6 class="card-title">Поведение и характер</h6>
                <p class="card-text">@Model.BehaviorCharacter</p>                
                <h6 class="card-title">История породы</h6>
                <p class="card-text">@Model.HistoryOfBreed</p>
                <a asp-action="Index" asp-controller="Dog" class="btn btn-outline-info">Открыть FCI стандарт</a>
                <a asp-action="Index" asp-controller="Dog" class="btn btn-outline-info">Назад</a>
            </div>
        </div>
    </div>
</div>

Views/Dog/Edit.cshtml
@model Dog
@{
    ViewData["Title"] = "Edit";
}

<h1>Отредактируйте данные</h1>


<div class="row">
    <div class="col-6">
        <form asp-controller="Dog" asp-action="Edit" method="post" enctype="multipart/form-data">
           <input name="ImageUrl" asp-for="ImageUrl" hidden/>
            <div class="form-group">
                <label asp-for="Breed"></label>
                <input asp-for="Breed" class="form-control" />
                <span asp-validation-for="Breed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BreedInEnglish"></label>
                <input asp-for="BreedInEnglish" class="form-control" />
                <span asp-validation-for="BreedInEnglish" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Origin"></label>
                <input asp-for="Origin" class="form-control" />
                <span asp-validation-for="Origin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FCICategoryId"></label>
                <select asp-for="FCICategoryId" asp-items="ViewBag.fciCategories" class="form-control">
                </select>
            </div>
            <div class="form-group">
                <label asp-for="DogTags"></label>
                <select name="tags" asp-items="ViewBag.tags" multiple class="form-select chosen-select">
                </select>
            </div>

            <img src="@Model.ImageUrl" height="200" />

            <div class="mb-3">
                <label for="formFile" class="form-label">Измените изображение</label>
                <input class="form-control" name="Image" type="file" id="formFile">
            </div>
            <div class="form-group">
                <label asp-for="BehaviorCharacter"></label> 
                <textarea asp-for="BehaviorCharacter" class="form-control" rows="10"></textarea>
                <span asp-validation-for="BehaviorCharacter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HistoryOfBreed"></label>
                <textarea asp-for="HistoryOfBreed" class="form-control" rows="10"></textarea>
                <span asp-validation-for="HistoryOfBreed" class="text-danger"></span>
            </div>
            <button class="btn btn-outline-primary w-25 mt-2">Изменить</button>
        </form>
    </div>
</div>


@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Views/Dog/Index.cshtml
@model IndexViewModel
@{
    ViewData["Title"] = "Home Page";
}

@*@await Component.InvokeAsync("Pagination")*@

@if (TempData.ContainsKey("status"))
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>@TempData["status"]</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}


<div class="text-center">
    <h1 class="display-4">Все породы</h1>
    <form asp-action="Index" asp-controller="Dog" method="get" class="input-group mb-3">
        <input required name="searchBreed" type="text" class="form-control" placeholder="Название породы" aria-label="Recipient's username" aria-describedby="button-addon2">
        <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Поиск</button>
    </form>
</div>

<div class="row">
    <div class="col-2">
        <div class="row">
            <h3>Группа FCI</h3>
            <hr />
            <div class="list-group">
                @if (Model.FCICategories != null)
                {
                    foreach (var item in @Model.FCICategories)
                    {
                        <a asp-action="Index" asp-controller="Dog" asp-route-fciCategoryId="@item.Id" asp-route-tagId="@Model.SelectedTagId"
                        class="list-group-item list-group-item-action @(Model.SelectedFCICategoryId==item.Id? "active":"")">FCI @item.Name</a>
                    }
                }
            </div>
        </div>
        <div class="row">
            <h3>Назначение</h3>
            <hr />
            <div class="list-group">
                @if (Model.Tags != null)
                {
                    foreach (var item in @Model.Tags)
                    {
                        <a asp-action="Index" asp-controller="Dog" asp-route-tagId="@item.Id" asp-route-fciCategoryId="@Model.SelectedFCICategoryId"
                           class="list-group-item list-group-item-action @(Model.SelectedTagId==item.Id? "active":"")">@item.Name</a>
                    }
                }

            </div>
            <hr />
            <a asp-controller="Dog" asp-action="Index" class="btn btn-outline-info">Сбросить все фильтры</a>
        </div>
    </div>
    <div class="col-10">
        <div class="row">
            @if (Model != null && Model.Dogs.Count() > 0)
            {
                @foreach (var item in Model.Dogs)
                {
                    <partial name="_DogCardPartial" model="@item"></partial>
                }
            }else if(Model.Dogs.Count()==0)
            {
                <h3>Нет результатов</h3>
            }
        </div>

    </div>

    <vc:pagination current-page="@Model.CurrentPages"
                   total-pages="@Model.TotalPages"
                   limit="@Model.LimitPage"
                   tag-id="@Model.SelectedTagId"
                   fci-categori-id="@Model.SelectedFCICategoryId"
                   action="Index" controller="Dog"></vc:pagination>


</div>
    